stages:
  - perform
  - result
  - cleanup

scotty-perform:
  stage: perform
  script:
    - echo "exec scotty experiment perform"
    - mkdir ./scotty #later from perform
    - echo "all informations from experiment, resources and workloads" > ./scotty/info.txt #example
    - git fetch
  artifacts:
    expire_in: "1 hrs"
    paths:
      - ./scotty
  tags:
    - runner
  environment:
    name: scotty

scotty-result:
  stage: result
  script:
    - echo "exec scotty experiment result"
    - cat ./scotty/info.txt
  tags:
    - runner
  dependencies:
    - scotty-perform
  environment:
    name: scotty

scotty-cleanup:
  stage: cleanup
  script:
    - echo "exec scotty experiment cleanup"
    - cat ./scotty/info.txt
  tags:
    - runner
  dependencies:
    - scotty-perform
  environment:
    name: scotty