stages:
  - perform
  - result

scotty-perform:
  stage: perform
  script:
    - echo "exec scotty experiment perform"
    - mkdir .scotty #later from perform
    - echo "all informations from experiment, resources and workloads" > .scotty/info.txt #example
  artifacts:
    expire_in: "1 hrs"
    paths:
      - .scotty
  tags:
    - scotty-agent
  environment:
    name: scotty

scotty-result:
  stage: result
  script:
    - echo "exec scotty experiment result"
    - cat .scotty/info.txt
  tags:
    - scotty-agent
  dependencies:
    - scotty-perform
  environment:
    name: scotty