stages:
  - run
  - result
  - clean

scotty-run:
  stage: run
  script:
    - printenv
    - echo $PASSWORD
    - scotty experiment schedule
  tags:
    - scotty
  
scotty-result:
  stage: result
  script:
    - scotty experiment results
  tags:
    - scotty
  
scotty-clean:
  stage: clean
  script:
    - scotty experiment clean
  tags:
    - scotty