stages:
  - prepare
  - execute
  - results
  - clean

scotty-prepare:
  stage: prepare
  script:
    - echo "prepare experiment and resources"
  tags:
    - scotty-gate
  
scotty-execute:
  stage: execute
  script:
    - echo "execute experiment and run workloads"
  tags:
    - scotty-gate

scotty-results:
  stage: results
  script:
    - echo "collect results from experiments"
  tags:
    - scotty-gate

scotty-clean:
  stage: clean
  script:
    - echo "clean experiments and resources"
  tags:
    - scotty-gate