stages:
  - prepare
  - execute
  - results
  - clean

scotty-prepare:
  stage: prepare
  script:
    - echo "prepare experiment and resources"
    - sleep 60
    - git fetch
  tags:
    - runner
  environment:
    name: scotty
  
scotty-execute:
  stage: execute
  script:
    - echo "execute experiment and run workloads"
  tags:
    - runner
  environment:
    name: scotty

scotty-results:
  stage: results
  script:
    - echo "collect results from experiments"
  tags:
    - runner
  environment:
    name: scotty

scotty-clean:
  stage: clean
  script:
    - echo "clean experiments and resources"
  tags:
    - runner
  environment:
    name: scotty